### ISSUE TITLE
Create Composition(s) for our resources

### ISSUE THREAD

**Issue by SEQUOIIA** [dfds/provider-confluent#9] opened 2022-02-03 12:49 UTC
- [x] Create Composition for Topic
- [x] Test Composition for Topic
- [ ] Create Composition that includes a ServiceAccount, APIKey & ACLs
- [ ] Test Composition that includes a ServiceAccount, APIKey & ACLs

**Comment by samidbb** [comment] 2022-03-24 09:05
Topic XRD https://github.com/dfds/crossplane-configuration-dfds/pull/36

**Comment by Centine** [comment] 2022-04-05 08:28
Dupe of another issue

**Closed by Centine** 2022-04-05 08:28 UTC
Labels: Priority: 0
